title: JiU
description: "Hacking and Cyber Security Blog"
author:
  name: "JiU Ban"
  email: "tara7004@korea.ac.kr"
  url: "http://jjiyou.com"

#https://github.com/pages-themes/hacker

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SomeHacker"
year : "2020"

#recently added
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 